# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseiOS
  pod 'SDWebImage'

  target 'BaseiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseiOSUITests' do
    # Pods for testing
  end
  
end
